#
# This source file is part of the Stanford Spezi open-source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  buildandtest_ios:
    name: Build and Test Swift Package iOS
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      artifactname: SpeziContact.xcresult
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: SpeziContact
  buildandtest_latest:
    name: Build and Test Swift Package iOS Latest
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      xcodeversion: latest
      swiftVersion: 6
      scheme: SpeziContact
      resultBundle: SpeziContactLatest.xcresult
      artifactname: SpeziContactLatest.xcresult
  buildandtest_visionos:
    name: Build and Test Swift Package visionOS
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      artifactname: SpeziContact-visionOS.xcresult
      resultBundle: SpeziContact-visionOS.xcresult
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: SpeziContact
      destination: "platform=visionOS Simulator,name=Apple Vision Pro"
  buildandtestuitests_ios:
    name: Build and Test UI Tests iOS
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      artifactname: TestApp.xcresult
      runsonlabels: '["macOS", "self-hosted"]'
      path: "Tests/UITests"
      scheme: TestApp
  buildandtestuitests_visionos:
    name: Build and Test UI Tests visionOS
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      artifactname: TestApp-visionOS.xcresult
      resultBundle: TestApp-visionOS.xcresult
      runsonlabels: '["macOS", "self-hosted"]'
      path: "Tests/UITests"
      scheme: TestApp
      destination: "platform=visionOS Simulator,name=Apple Vision Pro"
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [buildandtest_ios, buildandtest_latest, buildandtest_visionos, buildandtestuitests_ios, buildandtestuitests_visionos]
    uses: StanfordSpezi/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    with:
      coveragereports: SpeziContact.xcresult SpeziContactLatest.xcresult SpeziContact-visionOS.xcresult TestApp.xcresult TestApp-visionOS.xcresult
    secrets:
      token: ${{ secrets.CODECOV_TOKEN }}
